version: '3.0'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: brand
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
#     - /var/docker/volumes/mysql:/var/lib/mysql
#     - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306